### ISSUE TITLE
Hacer los menus colapsables

### ISSUE THREAD

**Issue by annabranco** [Adalab/dorcas-s3-ohana-group#20]

**Comment by andreinavargas** [comment]
resuelto aqui https://github.com/Adalab/dorcas-s3-ohana-group/pull/27/commits/cd58f9f69e35f843fd6df893a95046d201ccb832

**Comment by annabranco** [comment]
Yeeeeah Andre!!!!

Solo te has olvidado cerrar el Issue! 😉

**Comment by Imoa1991** [comment]
Andre cierro el issue, ya que esta acabado =)
